keys:
  # User keys
  - &users:
    - &geoffrey_mariner-1 age173mhqrnhztgrrjc5vykz4hxmku7kplsherscym3ummxyg9dtf5vqqq72u2
    - &geoffrey_mariner-3 age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
    - &geoffrey_mariner-4 age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
    - &geoffrey_voyager age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
    - &geoffrey_pioneer age1ahyztttw0jky84tzg5vzvhwvhy3c4ptw7zg4kv5jrn4ergjq2c3q4f76dv
    - &geoffrey_apollo age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
    - &geoffrey_artemis age18jgsuq5wf3jv426rhst5saxc3etz29te3dx3tugg7466tje3layqvtar5f
    - &geoffrey_cassini age1x7t6fc2ccamga64a6lz7kxjv4txplng8272jnfx0le2vkcpyvuxq0jphnx
    - &geoffrey_curiosity age158unsxrql4w5huz4pjrr50gswj3tcnm3lxwd8ae54ye26pk454xsm5jwcr
  # Host keys
  - &hosts:
    - &apollo age13aztsk4mqshur74tqayz8svgr5d2tez86lrv70a8cc8xmshphg9spj028y
    - &mariner-1 age1vj7hdhettxhphf26fzx66m8xf89ak2qlqt30kwfdlz8ctcnzeuqs6zqxjm
    - &cassini_host age1gxgv7t76sdc288yhea0gzfne5cmj5dg590z3zvk4ltw504lg259qnn8x5h
creation_rules:
  - path_regex: secrets/default.yaml
    key_groups:
      - age:
          - *geoffrey_mariner-1
          - *geoffrey_mariner-3
          - *geoffrey_mariner-4
          - *geoffrey_voyager
          - *geoffrey_pioneer
          - *geoffrey_apollo
          - *geoffrey_artemis
          - *geoffrey_cassini
          - *geoffrey_curiosity
          # host key: neededForUsers secrets (login password) are decrypted
          # before user homes exist, so only a HOST key can unlock them.
          - *cassini_host

  - path_regex: secrets/hosts/apollo.yaml
    key_groups:
      - age:
          - *apollo

  # - path_regex: secrets/hosts/artemis.yaml
  #   key_groups:
  #     - age:
  #         - *artemis

  - path_regex: secrets/network.yaml
    key_groups:
      - age:
          - *apollo
          - *mariner-1
