#ENC[AES256_GCM,data:bbiWlc9VcxXVsDOwjkl2aMJWNL/yd2DVJ0GvyrILFI8oYiCBr2ojmn9iO+w=,iv:PZ3Ot7G6GWMbPgchjVSIP9HfKv7RcFpI8ZnvIwvYXwU=,tag:Fk3YFxB6rymnZ1P426kY8Q==,type:comment]
#ENC[AES256_GCM,data:+gdsHvm3SWgoJS2ThaiHRvs50/+sq2R8JQ==,iv:C5yrYxR0yo2DhkzuTIYv/qU05g0l+pnqLHKleAcz0zk=,tag:CBo+TAed5S3SNYbKCwj9fg==,type:comment]
github-token: ENC[AES256_GCM,data:wdYXCm1ChcW39pP4PQDZdiccytOFxrw2k3oLUkkbUgM8wB89hr5K2BcWpmjIhH+7cm1pUjxJ9gLdftPpUvYEBESTiMnK++5exUw5X08GbBjwGfMGe9X6ZrwcX/Bx,iv:sv3VW99oiCIGNsbx/qi5oyD1si6ssQTHPLqd7IEOHK8=,tag:B1QMpNKj48TDQdVU1f+GTA==,type:str]
openai-api-key: ENC[AES256_GCM,data:XoiSKd28GttbtvWHvW4xU7TvzTdGOxNPBMFHi0oth2w8IwNzHnITW5WghevtipY4ywAULUOzKl+YkVc/cDG9T+bjeFPjIE/Wo5dwirb96G+W8ATJYbKvBQpox3yEvD3YZLU6bf8/TPgpYLUpY3i0KG0BsHOtsHqAz8pVcFtB0Z4CP0+dlbc3itFDdeejL4fBL5Lh8r8rEp6UV0lkLFib6bklTCA=,iv:SnFiFSXFNXJopGo9Dm7RUVUnRsbFKwJfkmRagHhErVE=,tag:8MTad4As2qhYLSGodl+9Yg==,type:str]
openai-project-id: ENC[AES256_GCM,data:QXJRwySsMgCNy0X6ShW5nG/h6+b+QyBA27N7zoc=,iv:AcwK+R452IBZJVkF+lJxPuIn36+fOd4q/KyI8PELQKM=,tag:JSBiHmh+0GH5u+PC+UbS+Q==,type:str]
anthropic-api-key: ENC[AES256_GCM,data:1D9JQTUAY5rtatUs/PTXmaQBOpf6ylBV5P8uoIteeZZt/aMfRo1GqeCnpsSU0ZyzOLiYeGKlMHHNAK607OyncPJsdREK6iU4KCH0noNQUZLyJzjPTyMbaxjKVwPDIuewTlkcitwBKI1ghbt6,iv:i+9HovZELWz6I1sUdqFEAKlEniTX+6tBYcsnckI1NYE=,tag:q5+DkHBruaupcAMVnuNn0g==,type:str]
fly-attic-stationboard: ENC[AES256_GCM,data:jp5AAAk3dGDtYtHreFn09D1Q6hnvPiNmyX2ixlBc61Upv/xz82QW58Cy8ioS0/G5AXxExfNYG/m1uERVpnT+auuWUIdpZnL1XFUX34uO+0jUny//s6uhjF3YtBmkpB/HGMFseKtxfxs8rl2IjsVMPNKnjM2oYxDWV7CP55UQnwf4UNzWh9cI5OkkbiFzz0BqcMK9uJ16VvLEve5KFdZZaMLQhQH1j/pyar4W+AA4HxpUAylPROWcWfGVAh0gohASsc6geJUCja256y2psgXeWwotvjQFPWkUZI37JivY0x3+7mMQmhroSJS/PU10WdTTJuhiKBeEbRYwyNiVIBAM8X9SKg+4ybK8BvxcDfdaAn7Jymcva2cOGXJEPbyihgvzS7cZKOOTZnBEL6n1iGKx,iv:1JohmVqXc1xIfnwk2rS6ziUfA2n2PfD22pTYZdLr0CA=,tag:kB1vlrm/p/PY5CZtLRXl3Q==,type:str]
openai-organization: ENC[AES256_GCM,data:o9x1PFjff3yu4zTkuEGeHlzgzd++iNYNCGTcaQ==,iv:/hyZ8Ow7+fzr8VrNzQ+lQE5047YKiCFxBFUjckbRvjI=,tag:G6XWFtdDUrCCWYqyhQHeJg==,type:str]
email-password: ENC[AES256_GCM,data:yg7ipoghBxhZKP0o+I7Yvqgrnw==,iv:0bORLamJcNAEWzlOYQFWgSMSptvI8LsjxxM0OWnX/oE=,tag:a5NlWVaI/k/bzCryxAgZ5A==,type:str]
gateframe-api-key: ENC[AES256_GCM,data:ikrxh01TW9dwbwQG0blDj1gettB4nV2BHrfIpnXaMFBBkweYIqP+EbMWvMFlJ6fiOKtOfsKNVCf5Bj/IrbSMuiXplw==,iv:lyw8UuIUMzxNYc11wOUTF1rAD9FSoCQc/+KGkBs8cOo=,tag:l7yk1nB6jM1Zj/QQWJAh6g==,type:str]
gateframe-api-key-200: ENC[AES256_GCM,data:RTLGy+nN0p9NT6qcpp76gwhQD4SLDIozZYIaA22yN3h2VzaKS39j20Uo8L4Uq4m6N5FCYgA4QEP9QNxHJBkn+OcZjA==,iv:eZa/PM/Ch2+TlYv0Bi7gyNb4HdRnBrNDQhbbtvPf/5c=,tag:+UiZ9fATzFfr1grPjIrcNA==,type:str]
gateframe-betika-api-key: ENC[AES256_GCM,data:AAq6ly2fXSwvkK6eCfObYbbvvBx3S6+ka8RU1A6iu3OKBEv+hnm8z3scKrhDwND3o7nYmxQ8yHdPTuymlG39wO659w==,iv:eDHJzU2Smb6iICrEbCgd8pJvqYvvdw2gBHQpHySRaHQ=,tag:j0tiSMGo6GBeCXkqtXcwtA==,type:str]
gateframe-qwen-api-key: ENC[AES256_GCM,data:a81VJjr4BnSCTW/ONqMw51kiTqb3iXfyrzARxEZOkTdd+l0dcZRE2CqTqa61uzWvVJpvb9L9j1WadrQMzXV20lT7sg==,iv:gEkxnGynUaO4Rl8Jji1NEsldaa0KtOrjv+CyJuqTpdo=,tag:ShY2OFCg+te1TELUqgdHmQ==,type:str]
tailscale-auth-key-value: ENC[AES256_GCM,data:pNEWewIYS7jX80f0+ypFpi0FJfWaUWyJgBL/48zzRmY5vlGucpPMotH7XF6Zm/02tpP4T+kAMJ27hJLv6g==,iv:M0I1VuePyLTRjKM5GWpBzSjO2v+Px929dw0E1q2cBvU=,tag:FQDuffFvxGjekIeaR3PCWA==,type:str]
tailscale-auth-key:
    env_key: ENC[AES256_GCM,data://7m/N7RNluPQdSvURI2gkZU,iv:OzexAONw9gS+1exEI2iRKxWK/Ow1Q6RCxjojbRqu6SQ=,tag:NgnuhAZEOCVdhXgyAYRg7A==,type:str]
    value: ENC[AES256_GCM,data:8XCG/x2dL+j1f9L1bNTSq2dnxUazsWMHVaaQuULLuIEEWa4CT9QreEOWKXicuehy0StmPUuMDDN2FyqAtA==,iv:KbHaN9nDJ0uRfp7XHXyXuzpiq8oF5x+ueVMBIt2XmUQ=,tag:ksQAk3fErIm3i1Ldzj9n1A==,type:str]
    description: ENC[AES256_GCM,data:uPArnMqj1h/zqMdSTKE1D1Fo0g==,iv:Sb2gfrmTMpJ/AT3Fv4BgNwb5CKr4I7+0JuCvu8WI9S4=,tag:eXsqhhJtoecSHzcmFbc79Q==,type:str]
    id: ENC[AES256_GCM,data:r5mnshSB7S6qgH4JXV7vuG4=,iv:bj7L5dXRSXt50090D7Vd8CzYTLIh8aEgT8xpqjPIIww=,tag:zH72Ogo7jjJi2p+PUAq9xQ==,type:str]
    type: ENC[AES256_GCM,data:WJf0DDuYFaY=,iv:P6CaY4YYMR4k9ziX05YmGZMLfm+NzT1IC+x9n9aUYB4=,tag:TZWsh07evbmQkqc9LxY1vg==,type:str]
    expires: ENC[AES256_GCM,data:rkRqdkF6OC+oOQTOHIParJOOk9mj+7wp,iv:hW19cKHsfvqNQ4HdHrRzO4KCyjd2Fsv192XtNV+d3Hk=,tag:yxdkipVA5vQ0Uxyy9a4MBQ==,type:str]
    created: ENC[AES256_GCM,data:581i0nS6m2Klx1FVGWGJuH0kdUYYz2jQ,iv:ijt1NySwGkmOcqoayhJ+jEn8uvtNja4FreI/pcChGuU=,tag:9fuAFBfeqcprAZqaZrwH0g==,type:str]
cachix-auth-token-value: ENC[AES256_GCM,data:OrcmrZUKupt72Aiv+/JubTl87u/E9oh44vA2Vh+cczR6jmqy+AV42efJQtLtRS7FAze7TD/f+OyDJiElpoBEDiSLeeIvrXoBRRy5aDnsdw7Yo696KwBHFRvKiEZq1n+Uk4AV3um90wyiqQW8tPzSvJcLTy4s6zHp3URo6DSc567jZ5ZvK8ACG8zGgX9CxliBybkCh1s=,iv:0Cf1Otpq7eVigU+FxRFdTNqZFTFA/IbBq53zfqdVuWs=,tag:utOsBfL9NFZ1359RLDFADQ==,type:str]
cachix-auth-token:
    env_key: ENC[AES256_GCM,data:oRU+5Z/7tgJnyorPmWPZqoc=,iv:ffm7SJLIbRxKk+lD1QMMdGoBvibZwIIhd7PPbZcp8to=,tag:zKIodQ8Nw50+tTgg9M+LoA==,type:str]
    value: ENC[AES256_GCM,data:7MhQxO7RvmPCkZLPE+yi69f6RDI6B8Jd2jJEDxcDPWWIxDwCH1+Sy0bZcsdO9uW4I2bXj9NKxnv2aiIIYE5wHg7kqg2jbokoAu2rqWAUcVN7CFOKA+pukZT298EsIVeQxUPXMSiKefVgr92hop/cuqO76zMtiApI5Y+fCt7WW67rF3oOcACWXBdTp/xByr85iBJd7M4=,iv:QP8U9Edc0Rv2QeYpORGxElXcrgRQ9GSuSQzQdVeJN8o=,tag:p05Q3ws2a9mbmXvZr7APgQ==,type:str]
    description: ENC[AES256_GCM,data:SBxAjaX8ARYiOIiU6ZiAEw0dEq1Shw==,iv:blzrBuuTmQtQRYeHxLKjmibzvw95rUmI4IAY5oRJJNc=,tag:RJUBly35ooR+ilPrVbH7Nw==,type:str]
    permission:
        read: ENC[AES256_GCM,data:qddNaQ==,iv:JhI66D6ZeAhfRcWjuDdqbt5e6XlMmyQt/+2/hkzydgE=,tag:viQUuGGPL4Pjp7P2zxFcxQ==,type:bool]
        write: ENC[AES256_GCM,data:XbmfVg==,iv:N5Lo4cRrbtWJIy789PRQV2jt9UfLl2OZDKBn8Wv3jl4=,tag:YcH04Bqx4iPDrXQsAAYfbA==,type:bool]
    created: ENC[AES256_GCM,data:KmIHFhk9LK/yfirSnP/i+XjV8hbKbAmJ,iv:Jr1AT/lW5dvaRRSxnINcOl8jJq1EoJrBOZqpPr1mlpg=,tag:Ozrx4Is0fhVc10fxKtMS+g==,type:str]
    expires: ENC[AES256_GCM,data:nd8rYM9NO3GbNd6OzYDSNCFBSky+bW+1,iv:xy9HNcT07B5juQu+9q7mbBgajDvRyteB7HlTFxBE2Qo=,tag:b96L+XMrEk6JjbkKx1Yzlw==,type:str]
    action: ENC[AES256_GCM,data:vwMzA7B79MYrra9iI28ADi+hO7ql,iv:oGv+nLqHaJBxoWWfU4rrf7ZGh9nK/8Z/zTASS9f4T4o=,tag:aV7hq5yGnJMoChyieMN0zQ==,type:str]
smb-secrets: ENC[AES256_GCM,data:M7xe8CzbIihjULi9NpCqPo+ZerS+6SxCHrPn1VGOcMPxLW5TfR8w+4rGI5r0LEinaKxu1waoGlvu,iv:b3eMuRvYgLGkjRf5PjEkXXDxSIwWHGLldW69t8tL9HQ=,tag:B1OIw0+Y292wyCavB+AxUA==,type:str]
wireless_secrets: ENC[AES256_GCM,data:eLR1yLhJRo/l1ZOL7lQgAKfvNDSKoOmaD7bgwlZ4X8bALp2zOdXIp0SmRDsY6FK/K6iHVYRlNyGwbLdbW6fL21cO3SHbXEkqsxylP7nZLMw=,iv:W3jMiL4hd55Emf+0I1lsAHb6nxZKDaeptnSCZyUT9XA=,tag:0DBDptG/WsniRxNf1jtGIA==,type:str]
wpa_supplicant_conf: ENC[AES256_GCM,data:JXP1n30BLFNF6IskfiptMMccoNyFgOQj+fM7jJfmrI+fGnzQJRGUB9rgezN2QVdtUMcQOltKjK5VO+Kv5dSGmQrjGv4tiHv9WEZjoNK9IfWRVk2RAwwMZYcSXGDqPBFxk8KqshxlohMfuzkMRfqLFbAUeL+4RkCaQXrdMBhLC8VR3HjAEhqizWcGhcTLXI4VHoBFu3UHNjetpvCFd4PeUXBQsqlEOgLSOoKL+VjkuLBlcIea002syw1UqVN6576jnb+i5givFc/MYCLFrVD7SzR+LxOL1d0YtigyM+362BNzKgjUyrOtaGZ4Wm8PkAqyoaQD2ItrUYMP1KF9o3f+azP9RnULCN0cGvZQWf8ppmYcvy1aVH2mcztCyo0DBDxFHhng0sUe8DDojZ84pacg4Lt319eOLOWfj5/JZXlZI1TFvU9npLMF2kYwQHPTLZu41PBTTuv0WP9tW9B+gxvDBRehIYrIPpQ08jVFtb2MXZD6N7Cy+C4T5SCOPfLRIm6eSHrqGfR+t4zC7M1erSiyadV9v6wxel8Euv7x+JLPKyxmn7E=,iv:QSz/HPRrtwmwI9SNqAVudnTWLSuQMVFKE/iro1P/b8c=,tag:MoBWnMx7RPSn6Mi39AWeYw==,type:str]
redshift:
    latitude: ENC[AES256_GCM,data:9XgxjV/QFzM=,iv:aS0HcCJ2hLXh9nLkKe1ZcJeYwZ0UxmqZ4ftTZ2lnQNo=,tag:z+skAQ9Mpshp7Fr6nu7N1g==,type:float]
    longitude: ENC[AES256_GCM,data:cU9UP2/Yeg==,iv:yR58yiWyeyCrrouV7OruclDEFQvGTcfC34TOyMlh948=,tag:Q9WSXepjUWcSg1JU8y+bGw==,type:float]
k3s-token: ENC[AES256_GCM,data:jts0Eu2nOk5+Xyny3QXLNrtMACipfBUPs5R/Eb8KinjwHHDq2W58Ld/b1JpFrG2IBPsR96pS4TSYcTLwXRJGhKUGpvPldlSZOkplB7v18CsyHvHDXJJnksk/GdGXPrWUPC5Sal5uEj1onlCM,iv:QCp9USw5Dz5ENqE0qBPGqPhkHAFbMwQV0J7+yfYRT6s=,tag:5KKSAdHZF86mgYRZFm7Nog==,type:str]
users:
    geoffrey:
        password: ENC[AES256_GCM,data:PGt7YUcqqJsUJgCA7G0F7qI58E4qt4QfGMijjE2cqQNOVE1gY5B9juA7TIX0o54twagPfh6FwJGt2/E6C4mSi0NR0yPctUlp4A==,iv:J6PZStrY8m9shi9rL5aS4MNYwhi2pEzDwfVyWF0rtT0=,tag:YiD2Ife5IaNY1dtS/NlgPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OEl3cEVRa1Myay9ZQ1Bo
            SW0vYnBLSXdmZTdobUl3dXgwbktjajdoRHlzCnpJNFJNZnJub0xTWU0yYWdtZkJv
            YmVsYk1pbWZnZkp1bkhJUDRDb0hMemsKLS0tIFpUNHEyZHZwd2RQS0s5eG9SMXhj
            bmN0YlhMRTNtNjUxY3AvTzRGcTJkNU0KCbvF+W4EpXRmkBFL/yGnPQNwRmvARjXm
            QMF/kuAvGUP/sGS4bOm0Gpm01ChgDrb+FCBEX48+Q846rXuWC+YQkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age173mhqrnhztgrrjc5vykz4hxmku7kplsherscym3ummxyg9dtf5vqqq72u2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU0lqc0t0Tjl4SXoxVUha
            MkpqSzVSTTlUeTdmdEFKWGdlQzF1LzFHbHh3Cmh3citaeUxGeXJyVXd5MndqZWdR
            YjRDOHBHZDdaSGpHbEZhMnc3cEgxNG8KLS0tIFNNZjN6NGYxL3BBMVE3Uk9zZUdV
            M3NodXZWTG5nTnVMRnNpMjZsMnV5QVUKwhJu3F7w3DcGnN7vIslJgtgGloARkE/g
            /NN/a8aUvFF47bRxMVvP/xGOSYPaFMjOBwlZdHs+uY57Ahtnj1qvMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kdp9ndxywv48mapkkejujvzfqhxzyzp6s7kp42u7ynu6q5e8sqkqp0w7sv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR3AxbjJOb3ozV3hZNHBW
            TllGYWlLcVBkbkV5Tk0vL1BOUnFnaTYrTkRFCmV1bGJ4d3MxMEd4bUJSLzZ5L3dE
            Z0VYVFlrZHBUVVVzS28vR1MzZWRGUVkKLS0tIGdRVjd5ZEUvbFpFZ2hQcDh2RWFG
            dWV0NnBNRWtNVFVPWTFtb216VndNSk0K7gA26rY2fegI0pqJZIkskxZUY3him+ts
            XxW5FGuhfeKaY637R+IHgxHFf8O25Ieyy4o9p9SSF5ulw7OCTwdv6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpj92c7aqe8df7g3qf58vzcyevx53vhap3qkrxa9calpdtp5vvmqrd0de7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRGJZOXhKVjU0SHRIM210
            UE1ZZW9XdzB4Z1ZSa3JzTkpHRmZvMDBDTWhjCjcrdFJsTnhJM28zYzZiWlkyYWhw
            c0JPQ2ttREFRM2h2TnRDWFl4SUxiSFkKLS0tIDE3ck5wTjdIN2lIcTlaT1RNa1ZN
            UlY2U3BVVWVPUlNldWZDRWpEOHBkN0UKsu/p2AeMSlIHiBqrGwPn81RJyhfJocG7
            n5X1gNLPH/RH9DtOukgvV69CejDwt1uI+4n8xjtXAFycdeUbb1bZOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13sx384sda6z7lvg6arys4asl4j88t652y0r9km86n3xrsuh5hpzqndl9lp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVk41NVNEb2FHbGxxN3My
            VmV1ZEU3OE1LeENSR2JXdFdqQURCZEYvQVU4CjEvS3dyYmhLSTdPMDJjSUVmM1Bq
            bDA5ODhiSGN3NUNTa21kYkYyYXJrUk0KLS0tIHRTa3BsaVFQL0JSNllwS2NqTC9L
            MktWMWovWmJqZVNNQzZaOWRmcTVUTVkKOx81mbQXtUuk2AQnRUvRy+w7KaETz49v
            kAM8XLFKUBPzSwVhQ6Xw09lNsqiREDF626ESI1Tw8gsZKpaVEHG/Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ahyztttw0jky84tzg5vzvhwvhy3c4ptw7zg4kv5jrn4ergjq2c3q4f76dv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TWFtUkdrZ0lrZkp5aDdi
            OGluK0xHaDdTREUwMUtXSnhTcVdJZkJTRGhZCmE1ajhiYTlOeUkrVDRrWGdnT0JH
            aU1tVE52aFVRWjZmTkpHUUNqbVVNRFkKLS0tIE9INlgvY0lhU0pjK2tXWHRTYTha
            SXV2VnI2V2MwaEFPWUx4dVducTdMRWMK2ZCOpjUtts3hGKRzuN/cbYwOoX3p8+3X
            ApVhg/IHBkuDxw6e16J296GUmCqpxqrposHI7kLOszGuKmeq7Eeg5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z09vrs2ketcn244l43fjxgzuu22yp0q0tpkmh3s2grlqn8jgypeqgnnf9f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdDZ1eENid3ZjeFIyM25w
            T2FNNU1IQzIyRjNJbnIrY1ZDU1hvdGlQejJJCkY5V3VhaWgybWxibFFUazFmdS8v
            WTJnUEJYdVRWS2lrTC9mUHptai81OVkKLS0tIHJlZ0dkQzBSLzhldmY0UWduN0E3
            QlhWYzFjS0hUcmxYc2ZZS3JZNmt5WWsKhnb60RYzbjSHNz/EEAS7IofgpHfnmwBo
            EoT23+IQ1IsAX/cCKQAcSGXwZx+B8FKZBBgsDV4gSk0jGimfWwkEqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18jgsuq5wf3jv426rhst5saxc3etz29te3dx3tugg7466tje3layqvtar5f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRVM0eGhoMDJxdEp4dGxo
            NzJ1UHdvV3NRN05BRFZmNnh4NWpmcHJEMWpzCjB2MGNETVNaeTdGaytoTlhOSmQ4
            UVR2ZVcyN0VqK0paQ0NPQk0vOHFlSzAKLS0tIDI1bk12MlNJYWs5L3REbkZFTG5w
            VEh3OXU5RmJWcHVDeFRFYWFYUWlyZGcKsE7vyaLIhYSxtTkhRSS2V8TnIq7EkOF7
            bQZbz1SNM/dw1O360ZAxB+D8/gi7MjliYyMNBnQIWcR0/DxLJ/61gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x7t6fc2ccamga64a6lz7kxjv4txplng8272jnfx0le2vkcpyvuxq0jphnx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUmt5emZhMUoydmIwU1VP
            a3liZUYrYlZVbmxSb1ErSXpvVXlhMWpSQldVCjN6NUgzdlBIblhyK2pMcDdUcHpN
            dFVSRjNJWGlvM1hEWC9hd3psc2Z2L3cKLS0tICs4UHhZTXU0b2FCTTViaHE5UlhH
            bHpxemJvM0dvQThFZ2JERUZXMkZGTW8KtO97hHkdzUsO745/Vm7ha0aUwAp+KFLT
            QIHlcG+eScBLLHpDwXAV+YkTplFCgLqDNhaoaEs9ioeyP2iTUmyiDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158unsxrql4w5huz4pjrr50gswj3tcnm3lxwd8ae54ye26pk454xsm5jwcr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZXpyVWZWWHNLbDJPcVFn
            R0I4SDljaWhaV0RDb2hKd2lXQzEzdTkzTmxFCkFrZFIxTkdDbTFMN2hGTHJaSkR1
            djBsdkdLd2J0MElYcFV3K0pkWmZWb0kKLS0tIDVZOWdQdlhkMXRsZi8wQzFOZjE1
            RlhOazJaVngvOEoxWkhKVytwbXRwOE0KtMe3mmWNsCzmVqCXvQ5fkATfKOJjaaBT
            gn7tOAABFpricUkPQ2sqfRGd/CeDiKluklJmfNxh3eG2xoi2XpFOHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxgv7t76sdc288yhea0gzfne5cmj5dg590z3zvk4ltw504lg259qnn8x5h
    lastmodified: "2026-07-08T13:26:01Z"
    mac: ENC[AES256_GCM,data:/sGXlfrHoYq50yoqMxkSN92AmqQ73bi/psNShRozARyg8CLRmFbASQ/FjM9wNwCPVPPGegDKQKkjTv4JSVoLoMZq24VDsdhS+PqL31WTmjVCDcnrbnj6iR1R7k2AaRPt1X63heJ9lZMFKenU93tENg7dopGZZu+EMLAHbXGNb2U=,iv:4QShu+qOxNNz6NOlBGkASrg3VEL8naKOrY4ehr9YpeU=,tag:9fWHXIVX6mdj4RG0DJjGEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
